### ISSUE TITLE
Add just hostname and port to csp white list in addition to fully qualified hostname

### ISSUE THREAD

**Issue by jordanCain** [zowe/explorer-ui-server#13]
Currently we add the the full hostname i.e host.my.company.com:port whereas some users have network configuration that allows them to resolve via just host:port

**Comment by NakulManchanda** [comment]
@jordanCain i believe we can close this one.
We can provide any string value to to be used as iframe_ancestors header
Not sure if you agree, if yes, feel free to close this one, thanks!

**Comment by jordanCain** [comment]
Agreed, the config is now an extendable list in instance.env so users can resolve this issue with config changes
