### ISSUE TITLE
Update explorer-ui-server to produce a pax file

### ISSUE THREAD

**Issue by stevenhorsman** [zowe/explorer-ui-server#36]
Currently explorer-ui-server is published as npm and bundled into the explorer ui components and shipped 2 times. With the keyring support this adds an extra 90MB of space into the pax file and the build is failing with out of space problems. IF we create a pax for explroer-ui-server and ship that and remove the bundling it, it might be small enough to stop the build problems.

**Comment by NakulManchanda** [comment]
https://github.com/zowe/explorer-ui-server/pull/37
https://github.com/zowe/explorer-jes/pull/207
https://github.com/zowe/zowe-install-packaging/pull/1545

**Comment by NakulManchanda** [comment]
its a separate pax now
