### ISSUE TITLE
Explorers are not starting with a certificate from a keyring because of missing tags for keyring_js module files

### ISSUE THREAD

**Issue by vit-tomica** [zowe/explorer-ui-server#38]
Explorers are failing at the line
https://github.com/zowe/explorer-ui-server/blob/60bc3fd655d062cf94c9a1a0c8376225d2f5a72d/src/config.js#L21
because of new keyring_js and node-gyp-build modules in `components/explorer-xxx/bin/server/node_modules` path do not have files tagged as ascii (ISO8859-1).

I think building pipeline should be changed to fix the tagging.

**Comment by NakulManchanda** [comment]
**Problem** we identified is to **require to reinstall node_modules** on target machine with zowe 1.14 RC1

We suspect this part of packaging to be an issue:
https://github.com/zowe/explorer-jes/blob/c6acfc18b6929f7cc35d11b6ebf86342ea59bb33/.pax/prepare-workspace.sh#L60

As we already install node_modules on z/os, so we can remove above line if its creating an issue
https://github.com/zowe/explorer-jes/blob/c6acfc18b6929f7cc35d11b6ebf86342ea59bb33/.pax/pre-packaging.sh#L18

@jackjia-ibm suggested following:
https://github.com/zowe/explorer-jes/pull/214
https://github.com/zowe/explorer-mvs/pull/143
https://github.com/zowe/explorer-uss/pull/96

Here is build with above PR's:
https://wash.zowe.org:8443/view/Zowe/job/zowe-install-packaging/job/users%252Fjack%252Fexplorer-apps-tagging/

Testing:
- node v6 - zowe.pax - we produced did not work we still needed to reinstall node_modules to make it work

Would be great if somebody can verify:
- node v8 & node v12 with machine on keyring setup
@stevenhorsman @vit-tomica 
thanks!

**Comment by vit-tomica** [comment]
I tested the build with the following version :
node v12.13.0 - OK
node v8.17.0 - OK
node v6.17.0 - OK 
Explorers worked with a keyring on all three versions.
